[env:xiao-esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
    -DFW_VERSION=\"1.0.0\"
lib_deps =
    gilmaimon/ArduinoWebsockets @ ^0.5.4
